### PR TITLE
Use maliput's method for creating road network via plugin api.

### LINKED ISSUE #67: Use method fo creating road network via plugin provided by maliput
### Summary

Use method added at https://github.com/maliput/maliput/pull/512

### PR DESCRIPTION
**Pull request by francocipollone**
Part of https://github.com/maliput/maliput/issues/509
Matches https://github.com/maliput/maliput/pull/512
Resolves #67

### CODE REVIEW

**Review by agalbachicar — APPROVED** [review]
LGTM

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
@ros-pull-request-builder retest this please

**Comment by francocipollone** [comment]
Now it is passing, going in!

**Pull request merged**
